# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=160, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_ -]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_ -]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
